name: "Test GITHUB_REF expansion"
on:
  push:
  #release:
  #  types: [published]
    
    
jobs:
  test-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Test Github Ref Env Variable
        run: |
          echo "foo/bar:$GITHUB_REF"

      - name: Test Github Ref Env Variable replacement
        run: |
          echo "foo/bar:${GITHUB_REF#refs/heads/}"

      - name: Test Github Ref Env Variable no spaces
        run: |
          echo "foo/bar:${GITHUB_REF}"
          
      - name: Test Github Ref Context Variable
        run: |
          echo "foo/bar:${{ github.ref }}"
          
      - name: Test Github Ref syntax fail
        run: |
          echo "foo/bar:${ GITHUB_REF }"
