name: "Deploy to Production Registry"
on:
  push:
  #release:
  #  types: [published]
    
    
jobs:
  test-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Test Github Ref Env Variable
        run: |
          echo "foo/bar:$GITHUB_REF"
